# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  boot.extraModulePackages = [];

  boot.initrd.availableKernelModules = [
    "nvme"
    "sd_mod"
    "thunderbolt"
    "uas"
    "usbhid"
    "xhci_pci"
  ];

  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/9f554bb6-a7ce-4445-9ffe-7e3abc0c5e6f";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/CAC4-06A7";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  swapDevices = [
    {device = "/dev/disk/by-uuid/65f0e769-c601-4800-b197-cdc71acd83df";}
  ];
}
