# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  boot = {
    extraModulePackages = [];

    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usbhid"
      ];

      kernelModules = [];
    };

    kernelModules = ["kvm-amd"];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/c4b8b2b1-7e05-4649-805e-a568db569a31";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/1EC6-4FE0";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };
  };

  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  swapDevices = [
    {device = "/dev/disk/by-uuid/83f4b435-d72e-40e4-a8c6-fb67e871950e";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
