theme = "everforest_dark"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
mouse = false
shell = ["nu", "-c"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "selections",
  "primary-selection-length",
  "register",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
]

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"

[editor.whitespace.render]
tab = "all"

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
