[[language]]
auto-format = true
name = "css"

[language.formatter]
args = [".css"]
command = "prettierd"

[[language]]
auto-format = true
name = "html"

[language.formatter]
args = [".html"]
command = "prettierd"

[[language]]
auto-format = true
name = "scss"

[language.formatter]
args = [".scss"]
command = "prettierd"

# just
[[language]]
name = "just"
auto-format = true
formatter = { command = "just", args = ["--justfile", "/dev/stdin", "--dump"] }

# markdown
[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettierd", args = [".md"] }

# nix
[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra" }

# toml
[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["format", "-"] }
