[[language]]
auto-format = true
name = "just"

[language.formatter]
args = ["--justfile", "/dev/stdin", "--dump"]
command = "just"

[[language]]
auto-format = true
name = "markdown"

[language.formatter]
args = [".md"]
command = "prettierd"

[[language]]
auto-format = true
name = "nix"

[language.formatter]
command = "alejandra"

[[language]]
auto-format = true
name = "toml"

[language.formatter]
args = ["format", "-"]
command = "taplo"

[[language]]
auto-format = true
name = "css"

[language.formatter]
args = [".css"]
command = "prettierd"

[[language]]
auto-format = true
name = "haskell"

[[language]]
auto-format = true
name = "html"

[language.formatter]
args = [".html"]
command = "prettierd"

[[language]]
auto-format = true
name = "scss"

[language.formatter]
args = [".scss"]
command = "prettierd"

[language-server.haskell-language-server.config]
formattingProvider = "fourmolu"
