shell = "bash -c '{}'"

[[items]]
name = "fzf"
path = "https://github.com/tinted-theming/base16-fzf"
themes-dir = "bash"
hook = """
FZF_DEFAULT_OPTS="$( \
  source %f && env \
  | grep FZF_DEFAULT_OPTS \
  | sed "s/FZF_DEFAULT_OPTS=//g" \
)"; \
\
themes_file="${HOME}/.dotfiles/nushell/themes.toml"; \
\
sed -i "s/FZF_DEFAULT_OPTS = \\".*\\"//g" "${themes_file}"; \
\
echo "FZF_DEFAULT_OPTS = \\"${FZF_DEFAULT_OPTS}\\"" \
  >> "${themes_file}"; \
\
nu -c "open ~/.dotfiles/nushell/themes.toml |
  save --force ~/.dotfiles/nushell/themes.toml"
"""
