shell = "bash -c '{}'"

[[items]]
name = "fzf"
path = "https://github.com/tinted-theming/base16-fzf"
themes-dir = "bash"
hook = """
echo "FZF_DEFAULT_OPTS = \"$(source %f && env | grep FZF_DEFAULT_OPTS | sed "s/FZF_DEFAULT_OPTS=//g")\"" > "${HOME}/.dotfiles/nushell/themes.toml"
"""
