# TODO: finalize theme!

inherits = "base16_default"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }

# "keyword.control.conditional" = { fg = "magenta", modifiers = ["italic"] }

"markup.heading.1" = "red"
"markup.heading.2" = "yellow"
"markup.heading.3" = "green"
"markup.heading.4" = "cyan"
"markup.heading.5" = "blue"
"markup.heading.6" = "magenta"

# "markup.link.label" = "sapphire"
# "markup.link.url" = { fg = "yellow", modifiers = ["italic", "underlined"] }
# "markup.list.checked" = "green"
# "markup.list.unchecked" = "overlay2"
# "namespace" = { fg = "magenta", modifiers = ["italic"] }
# "operator" = "sky"
# "punctuation" = "overlay2"
# "punctuation.special" = "sky"
# rainbow = ["red", "peach", "yellow", "green", "sapphire", "lavender"]
# "string.regexp" = "pink"
# "string.special" = "blue"
# "string.special.symbol" = "red"
# "tag" = "blue"
# "type.enum.variant" = "teal"
# "ui.background" = { fg = "text", bg = "base" }

"ui.bufferline.active" = { fg = "magenta", bg = "default", underline = { color = "magenta", style = "line" } }

# "ui.cursor.insert" = { fg = "base", bg = "secondary_cursor_insert" }
# "ui.cursorline.primary" = { bg = "cursorline" }
# "ui.cursor.normal" = { fg = "base", bg = "secondary_cursor_normal" }
# "ui.cursor.primary" = { fg = "base", bg = "rosewater" }
# "ui.cursor.primary.insert" = { fg = "base", bg = "green" }
# "ui.cursor.primary.normal" = { fg = "base", bg = "rosewater" }
# "ui.cursor.primary.select" = { fg = "base", bg = "lavender" }
# "ui.cursor.select" = { fg = "base", bg = "secondary_cursor_select" }
# "ui.highlight" = { bg = "surface1", modifiers = ["bold"] }
# "ui.text.directory" = { fg = "blue" }
# "ui.text.focus" = { fg = "text", bg = "surface0", modifiers = ["bold"] }
# "ui.text" = "text"
# "ui.virtual.indent-guide" = "surface0"
# "ui.virtual.inlay-hint" = { fg = "surface1", bg = "mantle" }
# "ui.window" = { fg = "crust" }
# "variable.builtin" = "red"
# "variable.parameter" = { fg = "maroon", modifiers = ["italic"] }
